before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without development
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
sudo: false
cache: bundler
