bundler_args: --without development
language: ruby
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
script: bundle exec thor spec
